[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "", arb-sepolia = "" }

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink-local/=lib/chainlink-local/",
]

